# Generated by Django 4.2.3 on 2026-01-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('P', 'PUNE'), ('N', 'NASHIK')], max_length=100)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
